<?php


namespace backend\models\project;


use backend\models\admin\Admin;
use yii\helpers\ArrayHelper;

class ProjectAdmin extends \common\models\ProjectAdmin
{
    public $admin;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['project_id', 'admin_id'], 'required'],
            [['operator_id', 'status', 'created_at', 'updated_at'], 'integer'],
            [['project_id', 'admin_id'], 'string', 'max' => 100],
        ];
    }


    /**
     * 获取用户
     * @return array|\yii\db\ActiveRecord[]|null
     */
    public static function takeProjectAdminForSelect(){
        $result = Admin::find()->select(['id','username'])
            ->andFilterWhere(['<>','id',2])
            ->andFilterWhere(['status'=>1])->asArray()->all();
        if($result) return ArrayHelper::map($result,'id','username');
        return null;
    }

    public function load($data, $formName = null)
    {
        return parent::load($data, $formName); // TODO: Change the autogenerated stub
    }


}